language: node_js
node_js:
  - lts/*

cache:
  directories:
    - node_modules

before_install:
  - export TZ='Asia/Shanghai'
  - openssl aes-256-cbc -K $encrypted_f217180e22ee_key -iv $encrypted_f217180e22ee_iv -in .travis/id_rsa.enc -out .travis/id_rsa -d
  - cp .travis/id_rsa  ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - eval $(ssh-agent)
  - ssh-add ~/.ssh/id_rsa
  - cp .travis/ssh_config ~/.ssh/config
  - git config --global user.name "yzddhr"
  - git config --global user.email yzddahaoren@126.com

install:
  - npm install hexo-cli -g
  - npm install

script:
  - npm run deploy

branches:
  only:
    - master
